apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-workload-elastic
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kibana
    - podSelector:
        matchLabels:
          app: elasticsearch